//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIManager.SparxEA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIManager.SparxEA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LVL@ @TITLE@
        ///
        ///@CLASSIFIERDOCNODE@
        ///.
        /// </summary>
        internal static string ASCIIDocClassifiers {
            get {
                return ResourceManager.GetString("ASCIIDocClassifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[[@CLASSANCHOR@]]
        ///@LVL@ @CLASSNAME@
        ///_Class_
        ///
        ///@NOTES@
        ///
        ///@XREF@
        ///
        ///[cols=&quot;4,5,1,8&quot;,options=&quot;header&quot;,]
        ///|=======================================================================
        ///| Field Name | Field Type | Card. | Description
        ///@ATTRIBUTES@
        ///|=======================================================================
        ///.
        /// </summary>
        internal static string ASCIIDocClassTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LVL@ @TITLE@
        ///
        ///@CLASSDOCNODE@
        ///.
        /// </summary>
        internal static string ASCIIDocCommonClasses {
            get {
                return ResourceManager.GetString("ASCIIDocCommonClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LVL@ @TITLE@
        ///
        ///@CLASSDOCNODE@
        ///.
        /// </summary>
        internal static string ASCIIDocCommonClassesbackup {
            get {
                return ResourceManager.GetString("ASCIIDocCommonClassesbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :numbered:
        ///:toc: macro
        ///
        ///= OCPP 2.X: Messages
        ///v0.8 DRAFT, 2017-02-09
        ///:title-logo-image: ../../style/media/logo.png
        ///
        ///Copyright © 2010 – 2017 Open Charge Alliance. All rights reserved.
        ///
        ///This document is made available under the _*Creative Commons Attribution-NoDerivatives 4.0 International Public License*_ (https://creativecommons.org/licenses/by-nd/4.0/legalcode).
        ///
        ///@ASCIIDocCommonClasses@
        ///
        ///@ASCIIDocClassifiers@
        ///.
        /// </summary>
        internal static string ASCIIDocCommonTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocCommonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[[@CLASSANCHOR@]]
        ///@LVL@ @CLASSNAME@
        ///_Class_
        ///
        ///@NOTES@
        ///
        ///@XREF@
        ///.
        /// </summary>
        internal static string ASCIIDocEmptyClassTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocEmptyClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[[@ENUMANCHOR@]]
        ///@LVL@ @ENUMNAME@
        ///_Enumeration_
        ///
        ///@NOTES@
        ///
        ///@XREF@
        ///
        ///[cols=&quot;2,10&quot;,options=&quot;header&quot;,]
        ///|=======================================================================
        ///|*Value* |*Description*
        ///@TYPES@
        ///|=======================================================================
        ///.
        /// </summary>
        internal static string ASCIIDocEnumTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocEnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LVL@ Message-specific Classes
        ///
        ///@CLASSDOCNODE@
        ///.
        /// </summary>
        internal static string ASCIIDocMessageClasses {
            get {
                return ResourceManager.GetString("ASCIIDocMessageClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LVL@ Message-specific Classes
        ///
        ///@CLASSDOCNODE@
        ///.
        /// </summary>
        internal static string ASCIIDocMessageClassesbackup {
            get {
                return ResourceManager.GetString("ASCIIDocMessageClassesbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[@MESSAGEANCHOR@]]
        ///@LVL@ @MESSAGENAME@
        ///
        ///@MESSAGENOTES@
        ///
        ///@ASCIIDocMessageClasses@
        ///.
        /// </summary>
        internal static string ASCIIDocMessageTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :numbered:
        ///:toc: macro
        ///
        ///= OCPP 2.X: Messages
        ///v0.8 DRAFT, 2017-02-09
        ///:title-logo-image: ../../style/media/logo.png
        ///
        ///Copyright © 2010 – 2017 Open Charge Alliance. All rights reserved.
        ///
        ///This document is made available under the _*Creative Commons Attribution-NoDerivatives 4.0 International Public License*_ (https://creativecommons.org/licenses/by-nd/4.0/legalcode).
        ///
        ///[[operations]]
        ///== Operations
        ///.
        /// </summary>
        internal static string ASCIIDocOperationListTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocOperationListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[@OPERATIONANCHOR@]]
        ///@LVL@ @OPERATIONNAME@
        ///
        ///@OPERATIONNOTES@
        ///
        ///@ASCIIDocMessageTemplate@
        ///
        ///@ASCIIDocCommonClasses@
        ///
        ///@ASCIIDocClassifiers@
        ///.
        /// </summary>
        internal static string ASCIIDocOperationTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocOperationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[@CLASSIFIERANCHOR@]]
        ///@LVL@ @CLASSIFIERNAME@
        ///_Type_
        ///
        ///@NOTES@
        ///
        ///@XREF@
        ///
        ///[cols=&quot;2,8&quot;,options=&quot;header&quot;,]
        ///|===============================================
        ///|*Field Type* |*Description*
        ///@TYPES@
        ///|===============================================
        ///.
        /// </summary>
        internal static string ASCIIDocTypeTemplate {
            get {
                return ResourceManager.GetString("ASCIIDocTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///                                    CodeList: @NAME@
        ///   ========================================================================================
        ///   Creation date:           @TIMESTAMP@
        ///   Version:                 @VERSION@
        ///   Capability modeled by:   @AUTHOR@
        ///
        ///   Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///   
        ///   ...................................................................................... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodeListHeader {
            get {
                return ResourceManager.GetString("CodeListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administrativestatustype:	CodeType;
        ///addresstext:				TextType;
        ///amount:						AmountType;
        ///bagidtype:					IdentifierType;
        ///buildingnumber:				NumericType;
        ///calorificvaluetype:			MeasureType;
        ///countrycode:				CodeType;
        ///cftype:                    CodeType;
        ///chamberofcommerceid:       IdentifierType;
        ///classificationtype:			CodeType;
        ///code:                      CodeType;
        ///commenttype:               TextType;
        ///commenttexttype:			TextType;
        ///communicationstatustype:   CodeType;
        ///consentidtype:				IdentifierType;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDSN_LDT_MappingTable {
            get {
                return ResourceManager.GetString("EDSN_LDT_MappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--@HEADER@--&gt;
        ///&lt;gc:CodeListSet xmlns:gc=&quot;http://docs.oasis-open.org/codelist/ns/genericode/1.0/&quot;
        ///    xmlns:rule=&quot;http://docs.oasis-open.org/codelist/ns/rule/1.0/&quot;
        ///    xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///    xsi:schemaLocation=&quot;http://docs.oasis-open.org/codelist/ns/genericode/1.0/ 
        ///	http://docs.oasis-open.org/codelist/cs-genericode-1.0/xsd/genericode.xsd&quot;&gt;
        ///    
        ///    &lt;Identification&gt;
        ///        &lt;ShortName xml:lang=&quot;en&quot;&gt;@NAME@&lt;/ShortName&gt;
        ///        &lt;Version&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericodeSetTemplate {
            get {
                return ResourceManager.GetString("GenericodeSetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--@HEADER@--&gt;
        ///&lt;gc:CodeList xmlns:gc=&quot;http://docs.oasis-open.org/codelist/ns/genericode/1.0/&quot;
        ///    xmlns:rule=&quot;http://docs.oasis-open.org/codelist/ns/rule/1.0/&quot;
        ///    xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///    xsi:schemaLocation=&quot;http://docs.oasis-open.org/codelist/ns/genericode/1.0/ 
        ///	http://docs.oasis-open.org/codelist/cs-genericode-1.0/xsd/genericode.xsd&quot;&gt;
        ///    
        ///    &lt;Identification&gt;
        ///        &lt;ShortName xml:lang=&quot;en&quot;&gt;@NAME@&lt;/ShortName&gt;
        ///        &lt;LongName xm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenericodeTemplate {
            get {
                return ResourceManager.GetString("GenericodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swagger: &quot;2.0&quot;
        ///#========================================================================================
        ///#          OpenAPI 2.0 (Swagger) definition for API: &apos;@SERVICE@&apos;
        ///#========================================================================================
        ///# API owning agency:     Enexis 
        ///# API creation date:     @TIMESTAMP@
        ///# API version:           @VERSION@
        ///# API modeled by:        @AUTHOR@
        ///# Assigned Access Level: @ACCESSLEVEL@
        ///#
        ///# Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///#
        ///#... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenAPI20Header {
            get {
                return ResourceManager.GetString("OpenAPI20Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos; for service: &apos;@SERVICE@&apos;
        ///   ========================================================================================
        ///   Interface agency:         Enexis 
        ///   Interface creation date:  @TIMESTAMP@
        ///   Interface version:        @VERSION@
        ///   Interface modeled by:     @AUTHOR@
        ///   Assigned Access Level:    @ACCESSLEVEL@
        ///
        ///   Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPInterfaceHeader {
            get {
                return ResourceManager.GetString("SOAPInterfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos; for service: &apos;@SERVICE@&apos;
        ///   ========================================================================================
        ///   Interface agency:         Enexis 
        ///   Interface creation date:  @TIMESTAMP@
        ///   Interface version:        @VERSION@
        ///   Interface modeled by:     @AUTHOR@
        ///   Assigned Access Level:    @ACCESSLEVEL@
        ///
        ///   Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPInterfaceHeaderEnexis {
            get {
                return ResourceManager.GetString("SOAPInterfaceHeaderEnexis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos;
        ///   ========================================================================================
        ///   Interface agency:         Open Charge Alliance 
        ///   Interface creation date:  @TIMESTAMP@
        ///   Interface version:        @VERSION@
        ///
        ///   Copyright (C) Open Charge Alliance (2010 - @YEAR@). All Rights Reserved.
        ///   
        ///   ................................................................... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPInterfaceHeaderOCPP {
            get {
                return ResourceManager.GetString("SOAPInterfaceHeaderOCPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos; for service: &apos;@SERVICE@&apos;
        ///   ========================================================================================
        ///   Schema agency:            Enexis
        ///   Schema creation date:     @TIMESTAMP@
        ///   Capability version:       @VERSION@
        ///   Capability modeled by:    @AUTHOR@
        ///   Assigned access level:    @ACCESSLEVEL@
        ///
        ///   Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPSchemaHeader {
            get {
                return ResourceManager.GetString("SOAPSchemaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos; for service: &apos;@SERVICE@&apos;
        ///   ========================================================================================
        ///   Schema agency:            Enexis
        ///   Schema creation date:     @TIMESTAMP@
        ///   Capability version:       @VERSION@
        ///   Capability modeled by:    @AUTHOR@
        ///   Assigned access level:    @ACCESSLEVEL@
        ///
        ///   Copyright (C) Enexis (@YEAR@). All Rights Reserved.
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPSchemaHeaderEnexis {
            get {
                return ResourceManager.GetString("SOAPSchemaHeaderEnexis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///   ========================================================================================
        ///   @CAPABILITYTYPE@ &apos;@CAPABILITY@&apos;
        ///   ========================================================================================
        ///   Schema agency:            Open Charge Alliance
        ///   Schema creation date:     @TIMESTAMP@
        ///
        ///   Copyright (C) Open Charge Alliance (2010 - @YEAR@). All Rights Reserved.
        ///   
        ///   ........................................................................................
        ///   @CHANGELOG@
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOAPSchemaHeaderOCPP {
            get {
                return ResourceManager.GetString("SOAPSchemaHeaderOCPP", resourceCulture);
            }
        }
    }
}
